### ISSUE TITLE
As a player in-game I want to receive a new hand of comments after every round to keep the game interesting

### ISSUE THREAD

**Issue by RoVi80** [sopra-fs23-group-08/server#10]
Story: As a player in-game I want to be provided with a new hand of comments at the beginning of every game-round (not every betting round) 

Acceptance criteria: 

-  [x] #55
      - [ ] … is comprised of 6 comments. 
      - [ ] … contains 0-6 comments that are from the current (round-)video’s comment section (i.e., matching comments) 
- [x] #56
- [x] #57

Priority: critical 
Estimate: 4-8 h

**Comment by S3r4f1n** [comment]
Closed in commit: 937317224af2009d37736890c155ed60dcb2fcf8
