### ISSUE TITLE
As a player in-game I want to see small & big blind values automatically be deduced from the correct players to setup the betting

### ISSUE THREAD

**Issue by RoVi80** [sopra-fs23-group-08/server#11]
Story: As a player in-game I want the small and big blind to be forced to bet the small and big blind at the beginning of each game-round so the betting can begin. 

Acceptance criteria: 

- [x] #53
- [x] #54

Priority: critical 
Estimate: 4-8 h

**Comment by S3r4f1n** [comment]
Closed in commit: 236f74a333977cc6dc0c5824c7535abde7b33244
