### ISSUE TITLE
As a player in-game I want to see the pot & current bets to inform my game-decisions

### ISSUE THREAD

**Issue by RoVi80** [sopra-fs23-group-08/server#15]
Story : As a player in-game I want to see how high the bet for the current round is and how many points have been placed into the pot in total to decide on my game-decisions. 

Acceptance criteria: 

- [x] sopra-fs23-group-08/client#22
- [x] sopra-fs23-group-08/client#23

Priority: Critical 
Estimate: 4 h

**Comment by Dedphish** [comment]
Closed, commits linked in sub-tasks
