### ISSUE TITLE
At the end of a round a winner is declared and the winner has its score updated

### ISSUE THREAD

**Issue by RoVi80** [sopra-fs23-group-08/server#16]
Story: As a player I want to be notified of the winner at the end of every round and have points added/deduced accordingly to progress the game 

Acceptance criteria: 

- [x] #33
- [x] #34
- [x] #35

Priority: Critical 
Estimate: 10h

**Comment by S3r4f1n** [comment]
Closed with commit: b13043058db3686f39f24730337dbe72c82f7899
