### ISSUE TITLE
As a game host I want to modify the game settings to play according to my preferences

### ISSUE THREAD

**Issue by RoVi80** [sopra-fs23-group-08/server#5]
Story: As a game host I want to be able to modify the game settings to customize the game for my lobby. 

Acceptance criteria: 
Hosts should be able to: 

- [ ] #70
- [x] #71
- [x] #72
- [x] #73

Priority: medium 
Estimate: 20h

**Comment by S3r4f1n** [comment]
closed in commit: 75e3f23821757a301d712b5f4a0e03f18f3ef318
