### ISSUE TITLE
Implement exception propagation & handling in STOMP communication

### ISSUE THREAD

**Issue by Dedphish** [sopra-fs23-group-08/server#97]
Right now, when the BE throws an exception, the FE will not be notified properly. Usually it just won't get a reaction to it's Websocket messages. However, we need to be able to catch exceptions in the FE to react accordingly. This likely includes implementing a custom Stomp error handler in the springboot framework and registering it in WSConfig

**Comment by S3r4f1n** [comment]
Be implemented in Commit: 58badb447a2837dd34f4bb68494f6d5d3f4129b3

**Comment by S3r4f1n** [comment]
FE implemented in Commit: db5c96c955f25496e66047222f40a22831470913
FE improved in Commit: 81453a922210e1c15f91601412f18d5c79059271
